name: sample workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: my first workflow
              run: echo "hello, well come to github workflow"



    second_job:
        runs-on: ubuntu-latest
        steps:
            - name: my second workflow
              run: echo "how are you"

            - name: access git repo
              uses: actions/checkout@v4

            - name: list files
              run: ls
              
            - name: read this file
              run: cat */README.md